name: Docker Build

on: [ workflow_call ]

jobs:
  test:
    uses: lucascsl1/teste-aws-githubActions/.github/workflows/tests.yml@master
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Docker Build
      run: docker build -t aplicacao-treinamento .
