name: Deploy AWS

on: [ push ]

jobs:

  test:
    uses: lucascsl1/teste-aws-githubActions/.github/workflows/tests.yml@master

  build_and_push:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Maven Package
      run: mvn package -DskipTests

    - name: AWS Configure
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_KEY }}
        aws-region: sa-east-1
      
    - name: AWS Login
      run: aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 439246771946.dkr.ecr.sa-east-1.amazonaws.com

    - name: Docker Build
      run: docker build -t aplicacao_treinamento .

    - name: Docker Tag
      run: docker tag aplicacao_treinamento:latest 439246771946.dkr.ecr.sa-east-1.amazonaws.com/aplicacao_treinamento:latest
      
    - name: Docker Push
      run: docker push 439246771946.dkr.ecr.sa-east-1.amazonaws.com/aplicacao_treinamento:latest
